// Package render turns LogPipeline specs into one Vector aggregator config.
//
// Each team's events flow through a chain of components named <team>_<stage>
// (teams are DNS labels, so the underscore can't be part of a team name):
//
//	<team>_src_<name>   a Kafka source, or a filter on the shared agents source
//	<team>_in_<name>    tag with team and source; parse pod logs (podlogs.go)
//	<team>_ids          route events with a spillway.event_id to dedupe
//	<team>_dedupe       drop recently seen event IDs (feeder replays)
//	<team>_redact       mask PII             (unless redaction.disabled is set)
//	    ├─► cold_s3     the complete redacted stream   (if routing.cold)
//	    └─► <team>_sample   keep a share per level     (if sampling is set)
//	        <team>_budget   cap the event rate, split  (if budget is set)
//	                        across the aggregators
//	        <team>_hot      stamp pre-sink latency ─► hot_loki   (if routing.hot)
//
// Cold storage keeps everything; sampling and the budget only thin the hot
// path. Dropped events show up in Vector's component_discarded_events_total
// under the team's own component IDs, and every metric of a team component
// carries a team tag (metrics_by_team), so drops sum per team. Sinks are
// shared by all teams, so the number of disk buffers doesn't grow with the
// number of teams.
//
// Redaction is on by default: a pipeline masks every pattern unless its spec
// lists fewer or turns redaction off (docs/adr/0003).
//
// Data no team claims takes the platform defaults, which are the M1 pipeline
// with every pattern masked and pod logs parsed: the feeder topic goes to
// Loki (wikimedia -> redact_feed -> stamp -> loki) and pod logs go to Loki
// labelled by namespace, pod and container (agents -> pod_logs ->
// redact_pods -> loki_pods). A claimed topic or namespace leaves the default path. With no
// pipelines, Render returns the platform config: vector/aggregator/vector.yaml
// is generated from it.
package render

import (
	"bytes"
	"fmt"
	"slices"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"

	spillwayv1alpha1 "github.com/Andrew-Hinson/spillway/api/v1alpha1"
	"github.com/Andrew-Hinson/spillway/internal/redact"
)

// Options are the cluster endpoints the rendered config points at.
type Options struct {
	KafkaBootstrap string
	LokiEndpoint   string
	// PodLogsTopic is the Kafka topic the agent DaemonSet writes pod logs to.
	PodLogsTopic string
	// Cold is required if any pipeline routes to cold storage.
	Cold *ColdStorage
	// Platform is what flows when no team claims it.
	Platform Platform
	// Aggregators is how many aggregator pods run the config. Each enforces
	// its own share of a team's budget; 0 is taken as 1.
	Aggregators int
}

// Platform configures the default paths for unclaimed data.
type Platform struct {
	// FeederTopic is read with the M1 consumer group and sent to Loki
	// unchanged, unless a team reads it. Empty disables the path.
	FeederTopic string
	// PodLogs sends pod logs from namespaces no team claims to Loki.
	PodLogs bool
}

// ColdStorage is an S3-compatible bucket (Silo locally, S3 in the cloud).
type ColdStorage struct {
	Endpoint string // empty for AWS S3
	Bucket   string
	Region   string
}

// DefaultOptions returns the endpoints of the local kind stack.
func DefaultOptions() Options {
	return Options{
		KafkaBootstrap: "spillway-kafka-bootstrap.kafka.svc:9092",
		LokiEndpoint:   "http://loki.observability.svc:3100",
		PodLogsTopic:   "spillway.pods",
		Cold: &ColdStorage{
			Endpoint: "http://s3.storage.svc:9000",
			Bucket:   "spillway-cold",
			Region:   "us-east-1",
		},
		Platform: Platform{FeederTopic: "wikimedia.recentchange", PodLogs: true},
		// vector/aggregator/values.yaml runs two; the operator uses the
		// StatefulSet's actual replica count.
		Aggregators: 2,
	}
}

const header = "# Generated by the Spillway renderer from LogPipeline specs. Do not edit.\n"

// Render returns the aggregator config for pipelines as YAML. Output is
// deterministic: the same specs always render the same bytes.
func Render(pipelines []spillwayv1alpha1.LogPipeline, opts Options) ([]byte, error) {
	cfg, _, err := RenderWithTests(pipelines, opts)
	return cfg, err
}

// RenderWithTests also returns `vector test` cases covering every transform
// in the config. Run them with: vector test config.yaml tests.yaml
func RenderWithTests(pipelines []spillwayv1alpha1.LogPipeline, opts Options) (cfg, tests []byte, err error) {
	pipelines = slices.Clone(pipelines)
	sort.Slice(pipelines, func(i, j int) bool { return pipelines[i].Spec.Team < pipelines[j].Spec.Team })
	if err := checkConflicts(pipelines, opts); err != nil {
		return nil, nil, err
	}

	c := &config{
		sources:    map[string]any{},
		transforms: map[string]any{},
		sinks:      map[string]any{},
	}
	c.sources["internal_metrics"] = map[string]any{"type": "internal_metrics", "scrape_interval_secs": 15}

	var hot, cold []string
	for _, p := range pipelines {
		h, cl, err := c.addPipeline(p, opts)
		if err != nil {
			return nil, nil, fmt.Errorf("pipeline %s/%s: %w", p.Namespace, p.Name, err)
		}
		hot = append(hot, h...)
		cold = append(cold, cl...)
	}
	metrics := []string{"internal_metrics"}
	if len(pipelines) > 0 {
		metrics = []string{c.addTeamMetrics(pipelines)}
	}
	if c.addPlatform(pipelines, opts) {
		metrics = append(metrics, "latency_metrics")
	}
	if len(hot) > 0 {
		c.addHotSink(hot, opts, hotTeam(pipelines))
		metrics = append(metrics, "team_latency_metrics")
	}
	if len(cold) > 0 {
		c.addColdSink(cold, opts)
	}
	c.sinks["prometheus"] = map[string]any{
		"type":    "prometheus_exporter",
		"inputs":  metrics,
		"address": "0.0.0.0:9598",
		// Milliseconds; fine-grained below 100ms, where steady-state latency sits.
		"buckets": []float64{1, 2.5, 5, 10, 15, 20, 30, 50, 75, 100, 150, 250, 500, 1000, 2500, 5000, 10000, 30000, 60000},
	}

	out, err := yaml.Marshal(map[string]any{
		"data_dir": "/vector-data-dir",
		// Vector keeps each event's timestamp in a body field, "timestamp" by
		// default. Upstream events have their own "timestamp" (Wikimedia's is
		// Unix seconds), so Vector's goes under a reserved name: sources fill
		// it in and the Loki sinks use it as the entry time. (Log namespacing
		// would avoid the clash too, but in Vector 0.58 its timestamp is lost
		// in a disk buffer and Loki falls back to arrival time.)
		"log_schema": map[string]any{"timestamp_key": "_timestamp"},
		"api":        map[string]any{"enabled": true, "address": "0.0.0.0:8686"},
		"sources":    c.sources,
		"transforms": c.transforms,
		"sinks":      c.sinks,
	})
	if err != nil {
		return nil, nil, err
	}
	testsOut, err := yaml.Marshal(map[string]any{"tests": c.tests})
	if err != nil {
		return nil, nil, err
	}
	return append([]byte(header), out...), append([]byte(testsHeader), testsOut...), nil
}

// teamStages matches the component IDs addPipeline gives a team's
// components, capturing the team. Platform and shared components (stamp,
// redact_feed, hot_loki, team_latency_events…) never end in one of these
// stages.
const teamStages = `^(?P<team>[a-z0-9-]+)_(?:src_.+|in_.+|ids|dedupe|redact|sample|budget|hot)$`

// addTeamMetrics tags Vector's own metrics for each team's components with
// the team, so drops (sampling, budget, dedupe), throughput and errors can be
// summed per team. It returns the ID that feeds the Prometheus exporter.
func (c *config) addTeamMetrics(pipelines []spillwayv1alpha1.LogPipeline) string {
	teams := make([]string, len(pipelines))
	for i, p := range pipelines {
		teams[i] = p.Spec.Team
	}
	const id = "metrics_by_team"
	c.transforms[id] = remap([]string{"internal_metrics"}, fmt.Sprintf(`found = parse_regex(string(.tags.component_id) ?? "", r'%s') ?? {}
if includes(%s, found.team) { .tags.team = found.team }
`, teamStages, vrlStrings(teams)))
	c.testTeamMetrics(id, teams[0])
	return id
}

// hotTeam returns a team that routes hot, for tests of the shared metric.
func hotTeam(pipelines []spillwayv1alpha1.LogPipeline) string {
	for _, p := range pipelines {
		if hot(p) {
			return p.Spec.Team
		}
	}
	return ""
}

// checkConflicts catches what the CRD schema can't, because it spans objects.
func checkConflicts(pipelines []spillwayv1alpha1.LogPipeline, opts Options) error {
	teams := map[string]string{}
	namespaces := map[string]string{}
	for _, p := range pipelines {
		ref := p.Namespace + "/" + p.Name
		if other, ok := teams[p.Spec.Team]; ok {
			return fmt.Errorf("team %q is claimed by both %s and %s", p.Spec.Team, other, ref)
		}
		teams[p.Spec.Team] = ref
		for _, s := range p.Spec.Sources {
			if s.Kubernetes == nil {
				continue
			}
			for _, ns := range s.Kubernetes.Namespaces {
				if other, ok := namespaces[ns]; ok && other != ref {
					return fmt.Errorf("namespace %q is claimed by both %s and %s", ns, other, ref)
				}
				namespaces[ns] = ref
			}
		}
		if cold(p) && opts.Cold == nil {
			return fmt.Errorf("%s routes to cold storage, but no cold storage is configured", ref)
		}
	}
	return nil
}

type config struct {
	sources, transforms, sinks map[string]any
	tests                      []any
}

// addPipeline adds one team's components and returns the IDs that feed the
// hot and cold sinks.
func (c *config) addPipeline(p spillwayv1alpha1.LogPipeline, opts Options) (hotOut, coldOut []string, err error) {
	team := p.Spec.Team
	id := func(stage string) string { return team + "_" + stage }

	var inputs []string
	for _, s := range p.Spec.Sources {
		src, in := id("src_"+s.Name), id("in_"+s.Name)
		tag := fmt.Sprintf(".spillway.team = %q\n.spillway.source = %q\n", team, s.Name)
		switch {
		case s.Kafka != nil:
			// One consumer group per team and source, so teams reading the same
			// topic don't share (or steal) each other's offsets. A new team
			// starts at the head of the topic rather than replaying its whole
			// retention; restarts use committed offsets.
			c.sources[src] = kafkaSource(opts, fmt.Sprintf("spillway-%s-%s", team, s.Name), s.Kafka.Topic, "latest")
			c.transforms[in] = remap([]string{src}, "del(.source_type)\n"+tag)
			c.testKafkaIn(in, team, s.Name)
		case s.Kubernetes != nil:
			c.addAgentsSource(opts)
			c.transforms[src] = map[string]any{
				"type":      "filter",
				"inputs":    []string{"agents"},
				"condition": fmt.Sprintf("includes(%s, .kubernetes.pod_namespace)", vrlStrings(s.Kubernetes.Namespaces)),
			}
			c.transforms[in] = remap([]string{src}, podLogVRL+tag)
			c.testPodFilter(src, s.Kubernetes.Namespaces)
			c.testPodIn(in, team, s.Name, s.Kubernetes.Namespaces[0])
		default:
			return nil, nil, fmt.Errorf("source %q has no type", s.Name)
		}
		inputs = append(inputs, in)
	}

	// Everything after this point sees one merged stream per team.
	head := c.addDedupe(id("ids"), id("dedupe"), inputs)
	if patterns := redactionPatterns(p); len(patterns) > 0 {
		vrl, err := redact.VRL(patterns)
		if err != nil {
			return nil, nil, err
		}
		c.transforms[id("redact")] = remap(head, vrl)
		head = []string{id("redact")}
		c.testRedact(id("redact"), patterns)
	}
	if cold(p) {
		coldOut = head
	}
	if !hot(p) {
		return nil, coldOut, nil
	}

	if s := p.Spec.Sampling; s != nil && len(s.KeepPercent) > 0 {
		t := remap(head, samplingVRL(s))
		// An aborted event is dropped and counted as discarded.
		t["drop_on_abort"] = true
		c.transforms[id("sample")] = t
		c.testSample(id("sample"), s)
		head = []string{id("sample")}
	}
	if b := p.Spec.Budget; b != nil {
		c.transforms[id("budget")] = map[string]any{
			"type":        "throttle",
			"inputs":      head,
			"threshold":   BudgetPerPod(b.MaxEventsPerSec, opts.Aggregators) * budgetWindowSecs,
			"window_secs": budgetWindowSecs,
		}
		head = []string{id("budget")}
		c.testBudget(id("budget"))
	}
	c.transforms[id("hot")] = remap(head, stampVRL)
	c.testStamp(id("hot"))
	return []string{id("hot")}, coldOut, nil
}

// budgetWindowSecs is the throttle's window. Events reach an aggregator in
// batches (agent batches, Kafka fetches) that can be more than a second apart,
// and a throttle lets at most one window's threshold through at once, so a
// 1 s window wastes the budget between batches: with 10/s allowed and
// batches 1–2.5 s apart, vector passed 6.2/s. A 10 s window absorbs that and
// holds the same average, at the cost of letting a team that was idle send
// up to 10 s of budget at once (docs/adr/0005).
const budgetWindowSecs = 10

// BudgetPerPod is each aggregator's share of a team's maxEventsPerSec. Every
// pod runs its own throttle and there's no shared state between them, so the
// budget is split evenly, rounding down so the team-wide total never exceeds
// the spec. A budget smaller than the number of pods can't be split and
// becomes 1/s per pod.
func BudgetPerPod(maxEventsPerSec int32, aggregators int) int32 {
	if aggregators < 1 {
		aggregators = 1
	}
	return max(1, maxEventsPerSec/int32(aggregators))
}

// dedupeCache is how many recent event IDs each team remembers. At
// Wikimedia's ~40 events/s that's about four minutes, far longer than the
// replay after a feeder reconnects.
const dedupeCache = 10000

// addDedupe drops events whose spillway.event_id was seen recently: a
// feeder replaying after a reconnect keeps the upstream ID and Kafka key, so
// the replay reaches the same partition and aggregator. Vector's dedupe
// treats a missing field as a value, so every event without an ID would be a
// duplicate of the first; those bypass it. It returns the IDs that carry the
// stream on.
func (c *config) addDedupe(routeID, dedupeID string, inputs []string) []string {
	c.transforms[routeID] = map[string]any{
		"type":   "route",
		"inputs": inputs,
		"route":  map[string]any{"with_id": "is_string(.spillway.event_id)"},
	}
	c.transforms[dedupeID] = map[string]any{
		"type":   "dedupe",
		"inputs": []string{routeID + ".with_id"},
		"fields": map[string]any{"match": []string{"spillway.event_id"}},
		"cache":  map[string]any{"num_events": dedupeCache},
	}
	c.testDedupe(routeID, dedupeID)
	return []string{dedupeID, routeID + "._unmatched"}
}

// addAgentsSource adds the shared source of pod logs: the topic the agent
// DaemonSet writes to, read by every aggregator in one consumer group. The
// agents spread batches over its partitions, so each aggregator gets an even
// share of every namespace (which budgets rely on, docs/adr/0005). Pod logs
// are read from the oldest retained offset: unlike the feeder topics, nothing
// else holds them.
func (c *config) addAgentsSource(opts Options) {
	c.sources["agents"] = kafkaSource(opts, "spillway-pods", opts.PodLogsTopic, "earliest")
}

func (c *config) addHotSink(inputs []string, opts Options, team string) {
	c.sinks["hot_loki"] = map[string]any{
		"type":     "loki",
		"inputs":   inputs,
		"endpoint": opts.LokiEndpoint,
		"encoding": map[string]any{"codec": "json"},
		// Low-cardinality labels only; everything else stays in the JSON line.
		"labels": map[string]any{
			"team":   "{{ spillway.team }}",
			"source": "{{ spillway.source }}",
		},
		"out_of_order_action": "accept",
		"batch":               map[string]any{"timeout_secs": 1},
		"buffer":              diskBuffer(1 << 30),
		// Commit Kafka offsets only once events are buffered.
		"acknowledgements": map[string]any{"enabled": true},
	}
	// Feeder-to-sink latency as a histogram. Only events with a produce
	// timestamp (feeder events) have a latency to record.
	c.transforms["team_latency_events"] = map[string]any{
		"type":      "filter",
		"inputs":    inputs,
		"condition": "exists(.spillway.pipeline_latency_ms)",
	}
	c.transforms["team_latency_metrics"] = map[string]any{
		"type":    "log_to_metric",
		"inputs":  []string{"team_latency_events"},
		"metrics": []any{latencyHistogram(map[string]any{"team": "{{ spillway.team }}"})},
	}
	c.testLatencyFilter("team_latency_events")
	c.testLatencyMetric("team_latency_metrics", "team", team)
}

func latencyHistogram(tags map[string]any) map[string]any {
	return map[string]any{
		"type":      "histogram",
		"field":     "spillway.pipeline_latency_ms",
		"namespace": "spillway",
		"name":      "pipeline_latency_milliseconds",
		"tags":      tags,
	}
}

// addPlatform adds the default paths for data no team claims, and reports
// whether the feeder path (and so its latency metric) was added.
func (c *config) addPlatform(pipelines []spillwayv1alpha1.LogPipeline, opts Options) bool {
	var claimedNS []string
	topicClaimed := false
	for _, p := range pipelines {
		for _, s := range p.Spec.Sources {
			if s.Kubernetes != nil {
				claimedNS = append(claimedNS, s.Kubernetes.Namespaces...)
			}
			if s.Kafka != nil && s.Kafka.Topic == opts.Platform.FeederTopic {
				topicClaimed = true
			}
		}
	}

	if opts.Platform.PodLogs {
		c.addAgentsSource(opts)
		input := "agents"
		if len(claimedNS) > 0 {
			sort.Strings(claimedNS)
			c.transforms["unclaimed_pods"] = map[string]any{
				"type":      "filter",
				"inputs":    []string{"agents"},
				"condition": fmt.Sprintf("!includes(%s, .kubernetes.pod_namespace)", vrlStrings(claimedNS)),
			}
			input = "unclaimed_pods"
			c.testUnclaimedPods("unclaimed_pods", claimedNS)
		}
		c.transforms["pod_logs"] = remap([]string{input}, podLogVRL)
		c.testPlatformPodLogs("pod_logs")
		// Unclaimed data gets the strictest policy: no team has said it's PII-free.
		c.addPlatformRedact("redact_pods", "pod_logs")
		c.sinks["loki_pods"] = map[string]any{
			"type":     "loki",
			"inputs":   []string{"redact_pods"},
			"endpoint": opts.LokiEndpoint,
			"encoding": map[string]any{"codec": "json"},
			// Pod names change on every rollout, but a local cluster runs few
			// enough pods that the stream count stays small.
			"labels": map[string]any{
				"namespace": "{{ namespace }}",
				"pod":       "{{ pod }}",
				"container": "{{ container }}",
			},
			"remove_label_fields": true,
			"out_of_order_action": "accept",
			"batch":               map[string]any{"timeout_secs": 1},
			"buffer":              diskBuffer(512 << 20),
			// Commit pod-log offsets only once events are in this buffer.
			"acknowledgements": map[string]any{"enabled": true},
		}
	}

	if opts.Platform.FeederTopic == "" || topicClaimed {
		return false
	}
	c.sources["wikimedia"] = kafkaSource(opts, "spillway-aggregator", opts.Platform.FeederTopic,
		// The M1 consumer group predates teams and started from the oldest
		// retained event; it now resumes from its committed offsets.
		"earliest")
	c.addPlatformRedact("redact_feed", "wikimedia")
	c.transforms["stamp"] = remap([]string{"redact_feed"}, "del(.source_type)\n"+stampVRL)
	c.testStamp("stamp")
	c.transforms["latency_metrics"] = map[string]any{
		"type":    "log_to_metric",
		"inputs":  []string{"stamp"},
		"metrics": []any{latencyHistogram(map[string]any{"feeder": "{{ spillway.feeder }}"})},
	}
	c.testLatencyMetric("latency_metrics", "feeder", "wikimedia")
	c.sinks["loki"] = map[string]any{
		"type":     "loki",
		"inputs":   []string{"stamp"},
		"endpoint": opts.LokiEndpoint,
		"encoding": map[string]any{"codec": "json"},
		// Low-cardinality labels; wiki, title, user and so on stay in the line.
		"labels": map[string]any{
			"feeder": "{{ spillway.feeder }}",
			"type":   "{{ type }}",
		},
		"out_of_order_action": "accept",
		"batch":               map[string]any{"timeout_secs": 1},
		"buffer":              diskBuffer(1 << 30),
		// Commit Kafka offsets only once events are safely in the disk buffer.
		"acknowledgements": map[string]any{"enabled": true},
	}
	return true
}

// addPlatformRedact masks every pattern. Its ID can't clash with a team's
// components: those are <team>_<stage>, and "feed" and "pods" aren't stages.
func (c *config) addPlatformRedact(id, input string) {
	vrl, err := redact.VRL(redact.All())
	if err != nil {
		panic(err) // every built-in pattern has a filter
	}
	c.transforms[id] = remap([]string{input}, vrl)
	c.testRedact(id, redact.All())
}

func kafkaSource(opts Options, group, topic, offsetReset string) map[string]any {
	return map[string]any{
		"type":              "kafka",
		"bootstrap_servers": opts.KafkaBootstrap,
		"group_id":          group,
		"topics":            []string{topic},
		"auto_offset_reset": offsetReset,
		"decoding":          map[string]any{"codec": "json"},
		// Keep Kafka metadata out of the event body: it would overwrite
		// upstream fields with the same names and inflate every stored line.
		"key_field": "", "topic_key": "", "partition_key": "", "offset_key": "", "headers_key": "",
		"metrics": map[string]any{"topic_lag_metric": true},
	}
}

func (c *config) addColdSink(inputs []string, opts Options) {
	s := map[string]any{
		"type":   "aws_s3",
		"inputs": inputs,
		"bucket": opts.Cold.Bucket,
		"region": opts.Cold.Region,
		// Partitioned by team and day, so a team's history is one prefix.
		"key_prefix":  "team={{ spillway.team }}/date=%Y-%m-%d/",
		"compression": "gzip",
		"encoding":    map[string]any{"codec": "json"},
		"framing":     map[string]any{"method": "newline_delimited"},
		// Fewer, larger objects: cold storage is read rarely and in bulk.
		"batch":            map[string]any{"timeout_secs": 60, "max_bytes": 10 << 20},
		"buffer":           diskBuffer(512 << 20),
		"acknowledgements": map[string]any{"enabled": true},
	}
	if opts.Cold.Endpoint != "" {
		s["endpoint"] = opts.Cold.Endpoint
		// The local store serves buckets by path, not by subdomain.
		s["force_path_style"] = true
	}
	c.sinks["cold_s3"] = s
}

func remap(inputs []string, source string) map[string]any {
	return map[string]any{"type": "remap", "inputs": inputs, "source": source}
}

func diskBuffer(bytes int) map[string]any {
	return map[string]any{"type": "disk", "max_size": bytes, "when_full": "block"}
}

// redactionPatterns returns the patterns a pipeline masks: every one unless
// the spec lists some, and none if it turns redaction off.
func redactionPatterns(p spillwayv1alpha1.LogPipeline) []spillwayv1alpha1.RedactionPattern {
	r := p.Spec.Redaction
	switch {
	case r == nil || (!r.Disabled && len(r.Patterns) == 0):
		return redact.All()
	case r.Disabled:
		return nil
	}
	return r.Patterns
}

func hot(p spillwayv1alpha1.LogPipeline) bool {
	if r := p.Spec.Routing; r != nil && r.Hot != nil {
		return *r.Hot
	}
	return true // the CRD default
}

func cold(p spillwayv1alpha1.LogPipeline) bool {
	r := p.Spec.Routing
	return r != nil && r.Cold != nil && *r.Cold
}

// vrlStrings renders a VRL array of string literals. Callers pass only values
// the CRD has already restricted to DNS labels or level names.
func vrlStrings(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// samplingVRL keeps KeepPercent of each listed level. Levels not listed, and
// events without a level, are kept.
func samplingVRL(s *spillwayv1alpha1.Sampling) string {
	field := s.LevelField
	if field == "" {
		field = "level" // the CRD default
	}
	levels := make([]string, 0, len(s.KeepPercent))
	for l := range s.KeepPercent {
		levels = append(levels, l)
	}
	sort.Strings(levels)
	var keep bytes.Buffer
	for i, l := range levels {
		if i > 0 {
			keep.WriteString(", ")
		}
		fmt.Fprintf(&keep, "%q: %d", l, s.KeepPercent[l])
	}
	return fmt.Sprintf(`keep = {%s}
level = downcase(to_string(get(., %s) ?? null) ?? "")
percent = int(get(keep, [level]) ?? null) ?? 100
if random_int(0, 100) >= percent { abort }
`, keep.String(), vrlStrings(strings.Split(field, ".")))
}

// stampVRL records when an event leaves the pipeline, so sink_at -
// produced_at is the feeder-to-sink latency.
const stampVRL = `sink_at = now()
.spillway.sink_at = sink_at
produced_at, err = parse_timestamp(.spillway.produced_at, "%+")
if err == null {
  .spillway.pipeline_latency_ms = to_unix_timestamp(sink_at, unit: "milliseconds") -
    to_unix_timestamp(produced_at, unit: "milliseconds")
}
`
