// Package render turns LogPipeline specs into one Vector aggregator config.
//
// Each team's events flow through a chain of components named <team>_<stage>
// (teams are DNS labels, so the underscore can't be part of a team name):
//
//	<team>_src_<name>   a Kafka source, or a filter on the shared agents source
//	<team>_in_<name>    tag with team and source; reshape pod logs
//	<team>_redact       mask PII                       (if redaction is set)
//	    ├─► cold_s3     the complete redacted stream   (if routing.cold)
//	    └─► <team>_sample   keep a share per level     (if sampling is set)
//	        <team>_budget   cap the event rate         (if budget is set)
//	        <team>_hot      stamp pre-sink latency ─► hot_loki   (if routing.hot)
//
// Cold storage keeps everything; sampling and the budget only thin the hot
// path. Dropped events show up in Vector's component_discarded_events_total
// under the team's own component IDs. Sinks are shared by all teams, so the
// number of disk buffers doesn't grow with the number of teams.
//
// Data no team claims takes the platform defaults, which are the M1 pipeline:
// the feeder topic goes straight to Loki (wikimedia -> stamp -> loki) and pod
// logs go to Loki labelled by namespace, pod and container (agents ->
// pod_logs -> loki_pods). A claimed topic or namespace leaves the default
// path, so a team's redaction can't be bypassed. With no pipelines, Render
// returns exactly the M1 config: vector/aggregator/vector.yaml is generated
// from it.
package render

import (
	"bytes"
	"fmt"
	"slices"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"

	spillwayv1alpha1 "github.com/Andrew-Hinson/spillway/api/v1alpha1"
	"github.com/Andrew-Hinson/spillway/internal/redact"
)

// Options are the cluster endpoints the rendered config points at.
type Options struct {
	KafkaBootstrap string
	LokiEndpoint   string
	// AgentsAddress is where the aggregator listens for the agent DaemonSet.
	AgentsAddress string
	// Cold is required if any pipeline routes to cold storage.
	Cold *ColdStorage
	// Platform is what flows when no team claims it.
	Platform Platform
}

// Platform configures the default paths for unclaimed data.
type Platform struct {
	// FeederTopic is read with the M1 consumer group and sent to Loki
	// unchanged, unless a team reads it. Empty disables the path.
	FeederTopic string
	// PodLogs sends pod logs from namespaces no team claims to Loki.
	PodLogs bool
}

// ColdStorage is an S3-compatible bucket (MinIO locally, S3 in the cloud).
type ColdStorage struct {
	Endpoint string // empty for AWS S3
	Bucket   string
	Region   string
}

// DefaultOptions returns the endpoints of the local kind stack.
func DefaultOptions() Options {
	return Options{
		KafkaBootstrap: "spillway-kafka-bootstrap.kafka.svc:9092",
		LokiEndpoint:   "http://loki.observability.svc:3100",
		AgentsAddress:  "0.0.0.0:6000",
		Cold: &ColdStorage{
			Endpoint: "http://minio.storage.svc:9000",
			Bucket:   "spillway-cold",
			Region:   "us-east-1",
		},
		Platform: Platform{FeederTopic: "wikimedia.recentchange", PodLogs: true},
	}
}

const header = "# Generated by the Spillway renderer from LogPipeline specs. Do not edit.\n"

// Render returns the aggregator config for pipelines as YAML. Output is
// deterministic: the same specs always render the same bytes.
func Render(pipelines []spillwayv1alpha1.LogPipeline, opts Options) ([]byte, error) {
	pipelines = slices.Clone(pipelines)
	sort.Slice(pipelines, func(i, j int) bool { return pipelines[i].Spec.Team < pipelines[j].Spec.Team })
	if err := checkConflicts(pipelines, opts); err != nil {
		return nil, err
	}

	c := &config{
		sources:    map[string]any{},
		transforms: map[string]any{},
		sinks:      map[string]any{},
	}
	c.sources["internal_metrics"] = map[string]any{"type": "internal_metrics", "scrape_interval_secs": 15}

	var hot, cold []string
	for _, p := range pipelines {
		h, cl, err := c.addPipeline(p, opts)
		if err != nil {
			return nil, fmt.Errorf("pipeline %s/%s: %w", p.Namespace, p.Name, err)
		}
		hot = append(hot, h...)
		cold = append(cold, cl...)
	}
	metrics := []string{"internal_metrics"}
	if c.addPlatform(pipelines, opts) {
		metrics = append(metrics, "latency_metrics")
	}
	if len(hot) > 0 {
		c.addHotSink(hot, opts)
		metrics = append(metrics, "team_latency_metrics")
	}
	if len(cold) > 0 {
		c.addColdSink(cold, opts)
	}
	c.sinks["prometheus"] = map[string]any{
		"type":    "prometheus_exporter",
		"inputs":  metrics,
		"address": "0.0.0.0:9598",
		// Milliseconds; fine-grained below 100ms, where steady-state latency sits.
		"buckets": []float64{1, 2.5, 5, 10, 15, 20, 30, 50, 75, 100, 150, 250, 500, 1000, 2500, 5000, 10000, 30000, 60000},
	}

	out, err := yaml.Marshal(map[string]any{
		"data_dir": "/vector-data-dir",
		// Vector keeps each event's timestamp in a body field, "timestamp" by
		// default. Upstream events have their own "timestamp" (Wikimedia's is
		// Unix seconds), so Vector's goes under a reserved name: sources fill
		// it in and the Loki sinks use it as the entry time. (Log namespacing
		// would avoid the clash too, but in Vector 0.58 its timestamp is lost
		// in a disk buffer and Loki falls back to arrival time.)
		"log_schema": map[string]any{"timestamp_key": "_timestamp"},
		"api":        map[string]any{"enabled": true, "address": "0.0.0.0:8686"},
		"sources":    c.sources,
		"transforms": c.transforms,
		"sinks":      c.sinks,
	})
	if err != nil {
		return nil, err
	}
	return append([]byte(header), out...), nil
}

// checkConflicts catches what the CRD schema can't, because it spans objects.
func checkConflicts(pipelines []spillwayv1alpha1.LogPipeline, opts Options) error {
	teams := map[string]string{}
	namespaces := map[string]string{}
	for _, p := range pipelines {
		ref := p.Namespace + "/" + p.Name
		if other, ok := teams[p.Spec.Team]; ok {
			return fmt.Errorf("team %q is claimed by both %s and %s", p.Spec.Team, other, ref)
		}
		teams[p.Spec.Team] = ref
		for _, s := range p.Spec.Sources {
			if s.Kubernetes == nil {
				continue
			}
			for _, ns := range s.Kubernetes.Namespaces {
				if other, ok := namespaces[ns]; ok && other != ref {
					return fmt.Errorf("namespace %q is claimed by both %s and %s", ns, other, ref)
				}
				namespaces[ns] = ref
			}
		}
		if cold(p) && opts.Cold == nil {
			return fmt.Errorf("%s routes to cold storage, but no cold storage is configured", ref)
		}
	}
	return nil
}

type config struct {
	sources, transforms, sinks map[string]any
}

// addPipeline adds one team's components and returns the IDs that feed the
// hot and cold sinks.
func (c *config) addPipeline(p spillwayv1alpha1.LogPipeline, opts Options) (hotOut, coldOut []string, err error) {
	team := p.Spec.Team
	id := func(stage string) string { return team + "_" + stage }

	var inputs []string
	for _, s := range p.Spec.Sources {
		src, in := id("src_"+s.Name), id("in_"+s.Name)
		tag := fmt.Sprintf(".spillway.team = %q\n.spillway.source = %q\n", team, s.Name)
		// A rebuilt pod log has no .spillway yet, so it's set whole.
		podTag := fmt.Sprintf(".spillway = {\"team\": %q, \"source\": %q}\n", team, s.Name)
		switch {
		case s.Kafka != nil:
			// One consumer group per team and source, so teams reading the same
			// topic don't share (or steal) each other's offsets. A new team
			// starts at the head of the topic rather than replaying its whole
			// retention; restarts use committed offsets.
			c.sources[src] = kafkaSource(opts, fmt.Sprintf("spillway-%s-%s", team, s.Name), s.Kafka.Topic, "latest")
			c.transforms[in] = remap([]string{src}, "del(.source_type)\n"+tag)
		case s.Kubernetes != nil:
			c.addAgentsSource(opts)
			c.transforms[src] = map[string]any{
				"type":      "filter",
				"inputs":    []string{"agents"},
				"condition": fmt.Sprintf("includes(%s, .kubernetes.pod_namespace)", vrlStrings(s.Kubernetes.Namespaces)),
			}
			c.transforms[in] = remap([]string{src}, podLogVRL+podTag)
		default:
			return nil, nil, fmt.Errorf("source %q has no type", s.Name)
		}
		inputs = append(inputs, in)
	}

	// Everything after this point sees one merged stream per team.
	head := inputs
	if r := p.Spec.Redaction; r != nil && len(r.Patterns) > 0 {
		filters, err := redact.Filters(r.Patterns)
		if err != nil {
			return nil, nil, err
		}
		c.transforms[id("redact")] = remap(head, fmt.Sprintf(
			"# Redact every string in the event except Spillway's own metadata.\n"+
				"meta = .spillway\n. = redact(., filters: [%s])\n.spillway = meta\n",
			strings.Join(filters, ", ")))
		head = []string{id("redact")}
	}
	if cold(p) {
		coldOut = head
	}
	if !hot(p) {
		return nil, coldOut, nil
	}

	if s := p.Spec.Sampling; s != nil && len(s.KeepPercent) > 0 {
		t := remap(head, samplingVRL(s))
		// An aborted event is dropped and counted as discarded.
		t["drop_on_abort"] = true
		c.transforms[id("sample")] = t
		head = []string{id("sample")}
	}
	if b := p.Spec.Budget; b != nil {
		c.transforms[id("budget")] = map[string]any{
			"type":        "throttle",
			"inputs":      head,
			"threshold":   b.MaxEventsPerSec,
			"window_secs": 1,
		}
		head = []string{id("budget")}
	}
	c.transforms[id("hot")] = remap(head, stampVRL)
	return []string{id("hot")}, coldOut, nil
}

// addAgentsSource adds the shared source the agent DaemonSet sends pod logs to.
func (c *config) addAgentsSource(opts Options) {
	c.sources["agents"] = map[string]any{"type": "vector", "address": opts.AgentsAddress}
}

func (c *config) addHotSink(inputs []string, opts Options) {
	c.sinks["hot_loki"] = map[string]any{
		"type":     "loki",
		"inputs":   inputs,
		"endpoint": opts.LokiEndpoint,
		"encoding": map[string]any{"codec": "json"},
		// Low-cardinality labels only; everything else stays in the JSON line.
		"labels": map[string]any{
			"team":   "{{ spillway.team }}",
			"source": "{{ spillway.source }}",
		},
		"out_of_order_action": "accept",
		"batch":               map[string]any{"timeout_secs": 1},
		"buffer":              diskBuffer(1 << 30),
		// Commit Kafka offsets (and answer agents) only once events are buffered.
		"acknowledgements": map[string]any{"enabled": true},
	}
	// Feeder-to-sink latency as a histogram. Only events with a produce
	// timestamp (feeder events) have a latency to record.
	c.transforms["team_latency_events"] = map[string]any{
		"type":      "filter",
		"inputs":    inputs,
		"condition": "exists(.spillway.pipeline_latency_ms)",
	}
	c.transforms["team_latency_metrics"] = map[string]any{
		"type":    "log_to_metric",
		"inputs":  []string{"team_latency_events"},
		"metrics": []any{latencyHistogram(map[string]any{"team": "{{ spillway.team }}"})},
	}
}

func latencyHistogram(tags map[string]any) map[string]any {
	return map[string]any{
		"type":      "histogram",
		"field":     "spillway.pipeline_latency_ms",
		"namespace": "spillway",
		"name":      "pipeline_latency_milliseconds",
		"tags":      tags,
	}
}

// addPlatform adds the default paths for data no team claims, and reports
// whether the feeder path (and so its latency metric) was added.
func (c *config) addPlatform(pipelines []spillwayv1alpha1.LogPipeline, opts Options) bool {
	var claimedNS []string
	topicClaimed := false
	for _, p := range pipelines {
		for _, s := range p.Spec.Sources {
			if s.Kubernetes != nil {
				claimedNS = append(claimedNS, s.Kubernetes.Namespaces...)
			}
			if s.Kafka != nil && s.Kafka.Topic == opts.Platform.FeederTopic {
				topicClaimed = true
			}
		}
	}

	if opts.Platform.PodLogs {
		c.addAgentsSource(opts)
		input := "agents"
		if len(claimedNS) > 0 {
			sort.Strings(claimedNS)
			c.transforms["unclaimed_pods"] = map[string]any{
				"type":      "filter",
				"inputs":    []string{"agents"},
				"condition": fmt.Sprintf("!includes(%s, .kubernetes.pod_namespace)", vrlStrings(claimedNS)),
			}
			input = "unclaimed_pods"
		}
		c.transforms["pod_logs"] = remap([]string{input}, podLogVRL)
		c.sinks["loki_pods"] = map[string]any{
			"type":     "loki",
			"inputs":   []string{"pod_logs"},
			"endpoint": opts.LokiEndpoint,
			"encoding": map[string]any{"codec": "json"},
			// Pod names change on every rollout, but a local cluster runs few
			// enough pods that the stream count stays small.
			"labels": map[string]any{
				"namespace": "{{ namespace }}",
				"pod":       "{{ pod }}",
				"container": "{{ container }}",
			},
			"remove_label_fields": true,
			"out_of_order_action": "accept",
			"batch":               map[string]any{"timeout_secs": 1},
			"buffer":              diskBuffer(512 << 20),
			// Answer an agent's batch only once it's in this buffer.
			"acknowledgements": map[string]any{"enabled": true},
		}
	}

	if opts.Platform.FeederTopic == "" || topicClaimed {
		return false
	}
	c.sources["wikimedia"] = kafkaSource(opts, "spillway-aggregator", opts.Platform.FeederTopic,
		// The M1 consumer group predates teams and started from the oldest
		// retained event; it now resumes from its committed offsets.
		"earliest")
	c.transforms["stamp"] = remap([]string{"wikimedia"}, "del(.source_type)\n"+stampVRL)
	c.transforms["latency_metrics"] = map[string]any{
		"type":    "log_to_metric",
		"inputs":  []string{"stamp"},
		"metrics": []any{latencyHistogram(map[string]any{"feeder": "{{ spillway.feeder }}"})},
	}
	c.sinks["loki"] = map[string]any{
		"type":     "loki",
		"inputs":   []string{"stamp"},
		"endpoint": opts.LokiEndpoint,
		"encoding": map[string]any{"codec": "json"},
		// Low-cardinality labels; wiki, title, user and so on stay in the line.
		"labels": map[string]any{
			"feeder": "{{ spillway.feeder }}",
			"type":   "{{ type }}",
		},
		"out_of_order_action": "accept",
		"batch":               map[string]any{"timeout_secs": 1},
		"buffer":              diskBuffer(1 << 30),
		// Commit Kafka offsets only once events are safely in the disk buffer.
		"acknowledgements": map[string]any{"enabled": true},
	}
	return true
}

func kafkaSource(opts Options, group, topic, offsetReset string) map[string]any {
	return map[string]any{
		"type":              "kafka",
		"bootstrap_servers": opts.KafkaBootstrap,
		"group_id":          group,
		"topics":            []string{topic},
		"auto_offset_reset": offsetReset,
		"decoding":          map[string]any{"codec": "json"},
		// Keep Kafka metadata out of the event body: it would overwrite
		// upstream fields with the same names and inflate every stored line.
		"key_field": "", "topic_key": "", "partition_key": "", "offset_key": "", "headers_key": "",
		"metrics": map[string]any{"topic_lag_metric": true},
	}
}

func (c *config) addColdSink(inputs []string, opts Options) {
	s := map[string]any{
		"type":   "aws_s3",
		"inputs": inputs,
		"bucket": opts.Cold.Bucket,
		"region": opts.Cold.Region,
		// Partitioned by team and day, so a team's history is one prefix.
		"key_prefix":  "team={{ spillway.team }}/date=%Y-%m-%d/",
		"compression": "gzip",
		"encoding":    map[string]any{"codec": "json"},
		"framing":     map[string]any{"method": "newline_delimited"},
		// Fewer, larger objects: cold storage is read rarely and in bulk.
		"batch":            map[string]any{"timeout_secs": 60, "max_bytes": 10 << 20},
		"buffer":           diskBuffer(512 << 20),
		"acknowledgements": map[string]any{"enabled": true},
	}
	if opts.Cold.Endpoint != "" {
		s["endpoint"] = opts.Cold.Endpoint
		// MinIO serves buckets by path, not by subdomain.
		s["force_path_style"] = true
	}
	c.sinks["cold_s3"] = s
}

func remap(inputs []string, source string) map[string]any {
	return map[string]any{"type": "remap", "inputs": inputs, "source": source}
}

func diskBuffer(bytes int) map[string]any {
	return map[string]any{"type": "disk", "max_size": bytes, "when_full": "block"}
}

func hot(p spillwayv1alpha1.LogPipeline) bool {
	if r := p.Spec.Routing; r != nil && r.Hot != nil {
		return *r.Hot
	}
	return true // the CRD default
}

func cold(p spillwayv1alpha1.LogPipeline) bool {
	r := p.Spec.Routing
	return r != nil && r.Cold != nil && *r.Cold
}

// vrlStrings renders a VRL array of string literals. Callers pass only values
// the CRD has already restricted to DNS labels or level names.
func vrlStrings(ss []string) string {
	quoted := make([]string, len(ss))
	for i, s := range ss {
		quoted[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(quoted, ", ") + "]"
}

// podLogVRL keeps a pod log's message and identity and drops the rest of the
// Kubernetes metadata, as the M1 aggregator did.
const podLogVRL = `k = object(.kubernetes) ?? {}
. = {
  "_timestamp": ._timestamp,
  "message": .message,
  "stream": .stream,
  "node": k.pod_node_name,
  "namespace": k.pod_namespace,
  "pod": k.pod_name,
  "container": k.container_name
}
`

// samplingVRL keeps KeepPercent of each listed level. Levels not listed, and
// events without a level, are kept.
func samplingVRL(s *spillwayv1alpha1.Sampling) string {
	field := s.LevelField
	if field == "" {
		field = "level" // the CRD default
	}
	levels := make([]string, 0, len(s.KeepPercent))
	for l := range s.KeepPercent {
		levels = append(levels, l)
	}
	sort.Strings(levels)
	var keep bytes.Buffer
	for i, l := range levels {
		if i > 0 {
			keep.WriteString(", ")
		}
		fmt.Fprintf(&keep, "%q: %d", l, s.KeepPercent[l])
	}
	return fmt.Sprintf(`keep = {%s}
level = downcase(to_string(get(., %s) ?? null) ?? "")
percent = int(get(keep, [level]) ?? null) ?? 100
if random_int(0, 100) >= percent { abort }
`, keep.String(), vrlStrings(strings.Split(field, ".")))
}

// stampVRL records when an event leaves the pipeline, so sink_at -
// produced_at is the feeder-to-sink latency.
const stampVRL = `sink_at = now()
.spillway.sink_at = sink_at
produced_at, err = parse_timestamp(.spillway.produced_at, "%+")
if err == null {
  .spillway.pipeline_latency_ms = to_unix_timestamp(sink_at, unit: "milliseconds") -
    to_unix_timestamp(produced_at, unit: "milliseconds")
}
`
