package render

// Generated `vector test` cases. The renderer adds tests for each transform
// as it adds the transform, so every rendered config comes with a suite that
// covers all of its transforms. The assertions describe what each step must
// do (a redacted value is gone, a 0% level is dropped, a claimed namespace
// leaves the platform path), not how the VRL does it.

import (
	"fmt"
	"slices"
	"sort"
	"strings"

	spillwayv1alpha1 "github.com/Andrew-Hinson/spillway/api/v1alpha1"
	"github.com/Andrew-Hinson/spillway/internal/redact"
)

const testsHeader = "# Generated by the Spillway renderer: `vector test` cases for every transform in the matching config. Do not edit.\n"

// test is one vector unit test: an event inserted at a component, and either
// conditions on what comes out or an assertion that nothing does.
func (c *config) test(name, insertAt, input string, extractFrom string, asserts ...string) {
	t := map[string]any{
		"name":   name,
		"inputs": []any{map[string]any{"insert_at": insertAt, "type": "vrl", "source": input}},
	}
	if len(asserts) == 0 {
		t["no_outputs_from"] = []string{extractFrom}
	} else {
		t["outputs"] = []any{map[string]any{
			"extract_from": extractFrom,
			"conditions":   []any{map[string]any{"type": "vrl", "source": strings.Join(asserts, "\n") + "\n"}},
		}}
	}
	c.tests = append(c.tests, t)
}

// expectNone is a test that the component emits nothing for input.
func (c *config) expectNone(name, at, input string) { c.test(name, at, input, at) }

func vrlObject(fields string) string { return ". = {" + fields + "}" }

// podEvent is a pod log as the agents send it.
func podEvent(namespace string) string {
	return vrlObject(fmt.Sprintf(`"message": "hello", "stream": "stdout", "kubernetes": {"pod_namespace": %q, "pod_name": "app-0", "container_name": "app", "pod_node_name": "node-1", "pod_ip": "10.0.0.1", "pod_labels": {"app": "x"}}`, namespace))
}

func (c *config) testKafkaIn(id, team, source string) {
	c.test(id+" tags events with team and source", id,
		vrlObject(`"title": "x", "source_type": "kafka", "spillway": {"event_id": "e1", "feeder": "wikimedia"}`), id,
		fmt.Sprintf(`assert_eq!(.spillway.team, %q)`, team),
		fmt.Sprintf(`assert_eq!(.spillway.source, %q)`, source),
		`assert_eq!(.spillway.event_id, "e1")`,
		`assert_eq!(.title, "x")`,
		`assert!(!exists(.source_type))`)
}

func (c *config) testPodFilter(id string, namespaces []string) {
	for _, ns := range namespaces {
		c.test(fmt.Sprintf("%s passes pod logs from %s", id, ns), id, podEvent(ns), id,
			fmt.Sprintf(`assert_eq!(.kubernetes.pod_namespace, %q)`, ns))
	}
	c.expectNone(id+" drops pod logs from other namespaces", id, podEvent(otherNamespace(namespaces)))
}

// otherNamespace returns a namespace that isn't in namespaces.
func otherNamespace(namespaces []string) string {
	other := "not-claimed"
	for slices.Contains(namespaces, other) {
		other += "-x"
	}
	return other
}

func podLogAsserts(namespace string) []string {
	return []string{
		`assert_eq!(.message, "hello")`,
		`assert_eq!(.stream, "stdout")`,
		fmt.Sprintf(`assert_eq!(.namespace, %q)`, namespace),
		`assert_eq!(.pod, "app-0")`,
		`assert_eq!(.container, "app")`,
		`assert_eq!(.node, "node-1")`,
		`assert!(!exists(.kubernetes))`,
	}
}

func (c *config) testPodIn(id, team, source, namespace string) {
	c.test(id+" reshapes pod logs and tags them with team and source", id, podEvent(namespace), id,
		append(podLogAsserts(namespace),
			fmt.Sprintf(`assert_eq!(.spillway.team, %q)`, team),
			fmt.Sprintf(`assert_eq!(.spillway.source, %q)`, source))...)
}

func (c *config) testPlatformPodLogs(id string) {
	c.test(id+" keeps the message and pod identity and drops other metadata", id, podEvent("default"), id,
		podLogAsserts("default")...)
}

func (c *config) testUnclaimedPods(id string, claimed []string) {
	for _, ns := range claimed {
		c.expectNone(fmt.Sprintf("%s drops pod logs from %s, claimed by a team", id, ns), id, podEvent(ns))
	}
	other := otherNamespace(claimed)
	c.test(id+" passes pod logs from unclaimed namespaces", id, podEvent(other), id,
		fmt.Sprintf(`assert_eq!(.kubernetes.pod_namespace, %q)`, other))
}

func (c *config) testRedact(id string, patterns []spillwayv1alpha1.RedactionPattern) {
	sorted := slices.Clone(patterns)
	slices.Sort(sorted)
	for _, p := range slices.Compact(sorted) {
		v := redact.Example(p)
		c.test(fmt.Sprintf("%s masks %s", id, p), id,
			vrlObject(fmt.Sprintf(`"message": "contact: %s", "detail": {"note": %q}, "spillway": {"team": "t", "event_id": %q}`, v, v, v)), id,
			fmt.Sprintf(`assert!(!contains(string!(.message), %q), message: string!(.message))`, v),
			fmt.Sprintf(`assert!(!contains(string!(.detail.note), %q), message: string!(.detail.note))`, v),
			`assert!(starts_with(string!(.message), "contact: "))`,
			// Spillway's own metadata is never redacted.
			fmt.Sprintf(`assert_eq!(.spillway.event_id, %q)`, v))
	}
	c.test(id+" leaves values that only look like PII", id,
		vrlObject(fmt.Sprintf(`"message": %q, "spillway": {"team": "t"}`, redact.LookAlike)), id,
		fmt.Sprintf(`assert_eq!(.message, %q)`, redact.LookAlike))
}

func (c *config) testSample(id string, s *spillwayv1alpha1.Sampling) {
	field := s.LevelField
	if field == "" {
		field = "level"
	}
	path := vrlStrings(strings.Split(field, "."))
	event := func(level string) string {
		// Levels are matched case-insensitively, so send them upper-case.
		return fmt.Sprintf(`. = set!(value: {"message": "m"}, path: %s, data: %q)`, path, strings.ToUpper(level))
	}
	levels := make([]string, 0, len(s.KeepPercent))
	for l := range s.KeepPercent {
		levels = append(levels, l)
	}
	sort.Strings(levels)
	for _, l := range levels {
		switch s.KeepPercent[l] {
		case 0:
			c.expectNone(fmt.Sprintf("%s drops every %s event (0%%)", id, l), id, event(l))
		case 100:
			c.test(fmt.Sprintf("%s keeps every %s event (100%%)", id, l), id, event(l), id, `assert_eq!(.message, "m")`)
		}
		// Percentages in between are random per event, so not unit-testable.
	}
	unlisted := "unlisted"
	for s.KeepPercent[unlisted] != 0 || slices.Contains(levels, unlisted) {
		unlisted += "x"
	}
	c.test(id+" keeps levels it doesn't list", id, event(unlisted), id, `assert_eq!(.message, "m")`)
	c.test(id+" keeps events without a level", id, vrlObject(`"message": "m"`), id, `assert_eq!(.message, "m")`)
}

func (c *config) testBudget(id string) {
	c.test(id+" passes events within budget", id, vrlObject(`"message": "m"`), id, `assert_eq!(.message, "m")`)
}

// testStamp covers the pre-sink stamp (team <team>_hot and platform stamp).
func (c *config) testStamp(id string) {
	c.test(id+" stamps sink time and pipeline latency", id,
		vrlObject(`"source_type": "kafka", "spillway": {"event_id": "e1", "produced_at": "2026-01-01T00:00:00.123456789Z", "feeder": "wikimedia"}`), id,
		`assert!(is_timestamp(.spillway.sink_at))`,
		`assert!(int!(.spillway.pipeline_latency_ms) > 0)`,
		`assert_eq!(.spillway.event_id, "e1")`)
	c.test(id+" tolerates events without a produce timestamp", id, vrlObject(`"message": "m"`), id,
		`assert!(is_timestamp(.spillway.sink_at))`,
		`assert!(!exists(.spillway.pipeline_latency_ms))`)
}

func (c *config) testLatencyFilter(id string) {
	c.test(id+" passes events with a latency", id,
		vrlObject(`"spillway": {"team": "t", "feeder": "wikimedia", "pipeline_latency_ms": 12}`), id,
		`assert_eq!(.spillway.pipeline_latency_ms, 12)`)
	c.expectNone(id+" drops events without a latency", id, vrlObject(`"message": "pod log"`))
}

func (c *config) testLatencyMetric(id, tag, value string) {
	c.test(id+" records latency as a histogram", id,
		vrlObject(fmt.Sprintf(`"spillway": {%q: %q, "pipeline_latency_ms": 12}`, tag, value)), id,
		`assert_eq!(.name, "pipeline_latency_milliseconds")`,
		`assert_eq!(.namespace, "spillway")`,
		fmt.Sprintf(`assert_eq!(.tags.%s, %q)`, tag, value))
}
