// Package crd embeds the generated LogPipeline CRD, so tools can validate
// specs against the exact schema the API server enforces without a cluster.
package crd

import _ "embed"

// LogPipeline is the CRD manifest generated by `make generate`.
//
//go:embed spillway.dev_logpipelines.yaml
var LogPipeline []byte
